# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.message_pb2 as message__pb2


class sendParamsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendParamsToEdge = channel.unary_unary(
                '/message.sendParams/sendParamsToEdge',
                request_serializer=message__pb2.Message.SerializeToString,
                response_deserializer=message__pb2.Time.FromString,
                )
        self.sendParamsToCore = channel.unary_unary(
                '/message.sendParams/sendParamsToCore',
                request_serializer=message__pb2.Message.SerializeToString,
                response_deserializer=message__pb2.MessageResponse.FromString,
                )


class sendParamsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendParamsToEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendParamsToCore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_sendParamsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendParamsToEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.sendParamsToEdge,
                    request_deserializer=message__pb2.Message.FromString,
                    response_serializer=message__pb2.Time.SerializeToString,
            ),
            'sendParamsToCore': grpc.unary_unary_rpc_method_handler(
                    servicer.sendParamsToCore,
                    request_deserializer=message__pb2.Message.FromString,
                    response_serializer=message__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.sendParams', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class sendParams(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendParamsToEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.sendParams/sendParamsToEdge',
            message__pb2.Message.SerializeToString,
            message__pb2.Time.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendParamsToCore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/message.sendParams/sendParamsToCore',
            message__pb2.Message.SerializeToString,
            message__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
